project/__init__.py
from flask import Flask, render_template


######################################
#### Application Factory Function ####
######################################


def create_app():
    # Create the Flask application
    app = Flask(__name__)

    register_blueprints(app)
    register_error_pages(app)
    return app


########################
### Helper Functions ###
########################


def register_blueprints(app):
    # Import the blueprints
    from project.recipes import recipes_blueprint
    from project.blog import blog_blueprint

    # Since the application instance is now created, register each Blueprint
    # with the Flask application instance (app)
    app.register_blueprint(recipes_blueprint)
    app.register_blueprint(blog_blueprint)


def register_error_pages(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template("404.html"), 404

project/blog/__init__.py
"""
The `blog` blueprint handles displaying blog posts.
"""
from flask import Blueprint

blog_blueprint = Blueprint("blog", __name__, template_folder="templates")

from . import routes

project/blog/routes.py
from . import blog_blueprint
from flask import render_template, abort


blog_post_titles = [
    "packaging-models",
    "chaotic-order",
    "ml-ops",
    "security-scanning",
    "code-quality",
    "moon",
    "ml-pain-points",
]


@blog_blueprint.route("/blog/")
def blog():
    return render_template("blog/blog.html")


@blog_blueprint.route("/<blog_title>/")
def posts(blog_title):
    if blog_title not in blog_post_titles:
        abort(404)

    return render_template(f"blog/{blog_title}.html")


@blog_blueprint.route("/about/")
def about():
    return render_template("blog/about.html")


@blog_blueprint.route("/reservations/")
def reservations():
    return render_template("blog/reservations.html")

project/recipes/__init__.py
"""
The `recipes` blueprint handles displaying recipes.
"""
from flask import Blueprint

recipes_blueprint = Blueprint("recipes", __name__, template_folder="templates")

from . import routes

project/recipes/routes.py
from . import recipes_blueprint
from flask import render_template


titanic_recipes_names = [
    "titanic_notebooks",
    "titanic_packaging",
    "titanic_api",
    "titanic_cicd",
    "titanic_container",
    "titanic_testing",
    "titanic_aws",
]
ames_recipes_names = [
    "ames_notebooks",
    "ames_packaging",
    "ames_api",
    "ames_cicd",
    "ames_container",
    "ames_testing",
    "ames_aws",
]
nlp_recipes_names = ["setup", "docs", "lda", "cai", "connect", "rekognition"]
data_visualisation_recipes_names = ["matplotlib", "seaborn", "geoplots", "bokeh"]
deep_learning_recipes_names = ["nn", "cnns", "nltk", "rnns", "advanced_rnns", "gans"]
data_analysis_recipes_names = [
    "bike_sharing",
    "absenteism",
    "marketing",
    "bankruptcy",
    "shoppers",
    "credit_cards",
    "heart",
    "retail",
    "energy",
    "air_quality",
]
ml_recipes_names = [
    "neural_networks",
    "supervised_metrics",
    "preprocessing",
    "unsupervised_algorithms",
    "supervised_algorithms",
]
data_wrangling_recipes_names = ["diving", "sources", "secrets", "scraping", "databases"]
mlops_recipes_names = [
    "titanic",
    "ames",
    "roadmaps",
]


@recipes_blueprint.route("/")
def recipes():
    return render_template("recipes/recipes.html")


@recipes_blueprint.route("/nlp/")
def nlp_recipes():
    return render_template("recipes/nlp.html")


@recipes_blueprint.route("/data_visualisation/")
def data_visualisation_recipes():
    return render_template("recipes/data_visualisation.html")


@recipes_blueprint.route("/deep_learning/")
def deep_learning_recipes():
    return render_template("recipes/deep_learning.html")


@recipes_blueprint.route("/data_analysis/")
def data_analysis_recipes():
    return render_template("recipes/data_analysis.html")


@recipes_blueprint.route("/data_wrangling/")
def data_wrangling_recipes():
    return render_template("recipes/data_wrangling.html")


@recipes_blueprint.route("/ml/")
def ml_recipes():
    return render_template("recipes/ml.html")


@recipes_blueprint.route("/mlops/")
def mlops_recipes():
    return render_template("recipes/mlops.html")


@recipes_blueprint.route("/titanic/")
def titanic_recipes():
    return render_template("recipes/titanic.html")


@recipes_blueprint.route("/ames/")
def ames_recipes():
    return render_template("recipes/ames.html")


@recipes_blueprint.route('/404/')
def fourohfour_recipes():
    return render_template('recipes/404.html')

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Milliways</title>

        <!-- Favicons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicons/apple-touch-icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicons/favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicons/favicon-16x16.png') }}">
        <link rel="manifest" href="{{ url_for('static', filename='favicons/site.webmanifest') }}">
        <link rel="mask-icon" href="{{ url_for('static', filename='favicons/safari-pinned-tab.svg') }}" color="#333333">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicons/favicon.ico') }}" type="image/x-icon">
        <meta name="msapplication-TileColor" content="#333333">
        <meta name="theme-color" content="#000000">

        <!-- Local CSS file for styling the application-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base_style.css') }}">

        {{ font_awesome.load_js() }}

        <!-- Additional Styling -->
        {% block styling %}
        {% endblock %}

    </head>

    <body>
        <header>
            <h1><a href="https://tymyrddin.dev">Ty Myrddin Home</a></h1>
            <nav>
                <ul>
                    <li class="nav__item"><a href="/" class="nav__link">Milliways</a></li>
                    <li class="nav__item"><a href="{{ url_for('blog.blog') }}" class="nav__link">Cuisine Starlight Blog</a></li>
                    <li class="nav__item"><a href="{{ url_for('blog.about') }}" class="nav__link">About</a></li>
                    <li class="nav__item"><a href="{{ url_for('blog.reservations') }}" class="nav__link">Make a reservation</a></li>
                </ul>
            </nav>
        </header>

        <main class="content">
            <!-- child template -->
            {% block content %}
            {% endblock %}
        </main>

        <footer>
            <p><a href="https://www.tymyrddin.dev/">Ty Myrddin</a> - <a rel="me" href="https://mastodon.social/@barzh">Mastodon</a> - <a rel="me" href="https://tube.spdns.org/a/barzh/video-channels">Move IT tube</a> - <a rel="me" href="https://github.com/tymyrddin">GitHub</a> - <a rel="me" href="https://gitlab.com/tymyrddin">Gitlab</a></p>
        </footer>
    </body>
</html>

project/templates/blogpost.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blogpost_style.css') }}">
{% endblock %}

{% block content %}
<div class="blogpost-container card-overlay">
    <div class="blogpost__heading">
        {% block title %}
        {% endblock %}

        <h3>by Ty Myrddin</h3>

        {% block date %}
        {% endblock %}
    </div>

    <div class="blogpost__image">
        {% block image %}
        {% endblock %}
    </div>

    <div class="blogpost__article">
        {% block article %}
        {% endblock %}
    </div>

    <div class="blogpost__article">
        <hr>
        <p>
        Oh well. Last orders, please. <span style="float:right"> <strong>Waiter</strong></span></p>

    </div>
</div>
{% endblock %}

project/templates/recipe.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_style.css') }}">
{% endblock %}

{% block content %}
<div class="recipe-detail-container">
    <div class="recipe-title">
        {% block recipe_title %}
        {% endblock %}
    </div>

    <div class="recipe-description card-overlay">
        {% block recipe_description %}
        {% endblock %}
    </div>

    <div class="recipe-image">
        {% block recipe_image %}
        {% endblock %}
    </div>

    <div class="recipe-tips card-overlay">
        {% block recipe_tips %}
        {% endblock %}
    </div>

    <div class="recipe-ingredients card-overlay">
        {% block recipe_ingredients %}
        {% endblock %}
    </div>

    <div class="recipe-steps card-overlay">
        {% block recipe_steps %}
        {% endblock %}
    </div>
</div>
{% endblock %}