project/recipes/__init__.py
"""
The `recipes` blueprint handles displaying recipes.
"""
from flask import Blueprint

recipes_blueprint = Blueprint("recipes", __name__, template_folder="templates")

from . import routes

project/recipes/routes.py
from . import recipes_blueprint
from flask import render_template


titanic_recipes_names = [
    "titanic_notebooks",
    "titanic_packaging",
    "titanic_api",
    "titanic_cicd",
    "titanic_container",
    "titanic_testing",
    "titanic_aws",
]
ames_recipes_names = [
    "ames_notebooks",
    "ames_packaging",
    "ames_api",
    "ames_cicd",
    "ames_container",
    "ames_testing",
    "ames_aws",
]
nlp_recipes_names = ["setup", "docs", "lda", "cai", "connect", "rekognition"]
data_visualisation_recipes_names = ["matplotlib", "seaborn", "geoplots", "bokeh"]
deep_learning_recipes_names = ["nn", "cnns", "nltk", "rnns", "advanced_rnns", "gans"]
data_analysis_recipes_names = [
    "bike_sharing",
    "absenteism",
    "marketing",
    "bankruptcy",
    "shoppers",
    "credit_cards",
    "heart",
    "retail",
    "energy",
    "air_quality",
]
ml_recipes_names = [
    "neural_networks",
    "supervised_metrics",
    "preprocessing",
    "unsupervised_algorithms",
    "supervised_algorithms",
]
data_wrangling_recipes_names = ["diving", "sources", "secrets", "scraping", "databases"]
mlops_recipes_names = [
    "titanic",
    "ames",
    "roadmaps",
]


@recipes_blueprint.route("/")
def recipes():
    return render_template("recipes/recipes.html")


@recipes_blueprint.route("/nlp/")
def nlp_recipes():
    return render_template("recipes/nlp.html")


@recipes_blueprint.route("/data_visualisation/")
def data_visualisation_recipes():
    return render_template("recipes/data_visualisation.html")


@recipes_blueprint.route("/deep_learning/")
def deep_learning_recipes():
    return render_template("recipes/deep_learning.html")


@recipes_blueprint.route("/data_analysis/")
def data_analysis_recipes():
    return render_template("recipes/data_analysis.html")


@recipes_blueprint.route("/data_wrangling/")
def data_wrangling_recipes():
    return render_template("recipes/data_wrangling.html")


@recipes_blueprint.route("/ml/")
def ml_recipes():
    return render_template("recipes/ml.html")


@recipes_blueprint.route("/mlops/")
def mlops_recipes():
    return render_template("recipes/mlops.html")


@recipes_blueprint.route("/titanic/")
def titanic_recipes():
    return render_template("recipes/titanic.html")


@recipes_blueprint.route("/ames/")
def ames_recipes():
    return render_template("recipes/ames.html")


@recipes_blueprint.route('/404/')
def fourohfour_recipes():
    return render_template('recipes/404.html')

project/recipes/templates/recipes/ames.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ames/-/tree/main/notebooks">
            <img
              src="{{ url_for('static', filename='img/notebooks.png') }}"
              alt="Notebooks"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Developing the ML model</h2>
                <p class="recipe-badge badge1">Continuous Regression</p>
                <p class="recipe-badge badge2">Reproducibility for pipeline</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ames/-/tree/main/production-model-package">
            <img
              src="{{ url_for('static', filename='img/packaging.png') }}"
              alt="Wicker basket"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Packaging for production</h2>
                <p class="recipe-badge badge1">Configurations</p>
                <p class="recipe-badge badge2">Building</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ames/-/tree/main/api">
            <img
              src="{{ url_for('static', filename='img/api.png') }}"
              alt="API"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Exposing using Fast API</h2>
                <p class="recipe-badge badge1">REST API</p>
                <p class="recipe-badge badge2">Heroku</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ames/-/tree/main/ci-and-publishing">
            <img
              src="{{ url_for('static', filename='img/orb.png') }}"
              alt="Orb"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">CI and publishing</h2>
                <p class="recipe-badge badge1">CircleCI</p>
                <p class="recipe-badge badge2">Index server</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ames/-/tree/main/deploying-with-containers">
            <img
              src="{{ url_for('static', filename='img/container.png') }}"
              alt="Container"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Deploying with a container</h2>
                <p class="recipe-badge badge1">Docker creation</p>
                <p class="recipe-badge badge2">CI pipeline</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ames/-/tree/main/differential-testing">
            <img
              src="{{ url_for('static', filename='img/red_dragon.png') }}"
              alt="Red dragon"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Differential testing</h2>
                <p class="recipe-badge badge1">Back-to-back</p>
                <p class="recipe-badge badge2">Semantic</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ames/-/tree/main/iaas">
            <img
              src="{{ url_for('static', filename='img/clustering.png') }}"
              alt="Clustering"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Deploying to IaaS</h2>
                <p class="recipe-badge badge1">AWS ECS</p>
                <p class="recipe-badge badge2">Fargate</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes/templates/recipes/data_analysis.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/bike_sharing">
            <img
              src="{{ url_for('static', filename='img/bikes.png') }}"
              alt="Bikes in Amsterdam"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Bike sharing</h2>
                <p class="recipe-badge badge1">Weather</p>
                <p class="recipe-badge badge2">Seasons</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/absenteism">
            <img
              src="{{ url_for('static', filename='img/absent.png') }}"
              alt="Absent"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Absenteism at work</h2>
                <p class="recipe-badge badge1">Courier company</p>
                <p class="recipe-badge badge2">Brazil</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/marketing">
            <img
              src="{{ url_for('static', filename='img/marketing.png') }}"
              alt="Marketing"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">Analyzing marketing campaign data</h2>
                <p class="recipe-badge badge1">Prediction</p>
                <p class="recipe-badge badge2">Portuguese bank</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/bankruptcy">
            <img
              src="{{ url_for('static', filename='img/bankruptcy.png') }}"
              alt="Bankruptcy"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Company bankruptcy</h2>
                <p class="recipe-badge badge1">Prediction</p>
                <p class="recipe-badge badge2">Polish companies</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/shoppers">
            <img
              src="{{ url_for('static', filename='img/shopping.png') }}"
              alt="Shopping bag"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Online shoppers</h2>
                <p class="recipe-badge badge1">Purchasing intention</p>
                <p class="recipe-badge badge2">Turkey</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/credit_cards">
            <img
              src="{{ url_for('static', filename='img/credit_cards.png') }}"
              alt="Credit cards"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Credit card defaulters</h2>
                <p class="recipe-badge badge1">Predictive accuracy</p>
                <p class="recipe-badge badge2">Taiwan</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/heart">
            <img
              src="{{ url_for('static', filename='img/heart.png') }}"
              alt="Heart"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Heart disease</h2>
                <p class="recipe-badge badge1">Prediction</p>
                <p class="recipe-badge badge2">Multivariate</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/retail">
            <img
              src="{{ url_for('static', filename='img/retail.png') }}"
              alt="Retail"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Online retail</h2>
                <p class="recipe-badge badge1">Non-store</p>
                <p class="recipe-badge badge2">Transactions</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/energy">
            <img
              src="{{ url_for('static', filename='img/energy_appliances.png') }}"
              alt="Energy appliances"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Energy consumed by appliances</h2>
                <p class="recipe-badge badge1">Regression</p>
                <p class="recipe-badge badge2">Wireless sensor network</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-analysis/-/tree/main/source/notebooks/air_quality">
            <img
              src="{{ url_for('static', filename='img/air_quality.png') }}"
              alt="Air quality"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Analyzing air quality</h2>
                <p class="recipe-badge badge1">Variables</p>
                <p class="recipe-badge badge2">Beijing</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes/templates/recipes/data_visualisation.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-visualisation/-/tree/main/source/notebooks/matplotlib">
            <img
              src="{{ url_for('static', filename='img/boxplots.png') }}"
              alt="Plunging in"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Matplotlib</h2>
                <p class="recipe-badge badge1">Customisations</p>
                <p class="recipe-badge badge2">TeX</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-visualisation/-/tree/main/source/notebooks/seaborn">
            <img
              src="{{ url_for('static', filename='img/seaborn.png') }}"
              alt="Data sources"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Seaborn</h2>
                <p class="recipe-badge badge1">Advantages</p>
                <p class="recipe-badge badge2">Built-in</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-visualisation/-/tree/main/source/notebooks/bokeh">
            <img
              src="{{ url_for('static', filename='img/bokeh.png') }}"
              alt="Data gathering"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Bokeh</h2>
                <p class="recipe-badge badge1">Interactive</p>
                <p class="recipe-badge badge2">Web-based visualisations</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes/templates/recipes/data_wrangling.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-wrangling/-/tree/main/source/notebooks/diving">
            <img
              src="{{ url_for('static', filename='img/manipulation.png') }}"
              alt="Plunging in"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Plunging in</h2>
                <p class="recipe-badge badge1">Goosnargh</p>
                <p class="recipe-badge badge2">Perfectly ordinary</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-wrangling/-/tree/main/source/notebooks/sources">
            <img
              src="{{ url_for('static', filename='img/well.png') }}"
              alt="Data sources"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Data sources</h2>
                <p class="recipe-badge badge1">Zarking</p>
                <p class="recipe-badge badge2">Photon</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-wrangling/-/tree/main/source/notebooks/secrets">
            <img
              src="{{ url_for('static', filename='img/data_secrets.png') }}"
              alt="Some secrets"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Some secrets</h2>
                <p class="recipe-badge badge1">Universe</p>
                <p class="recipe-badge badge2">Everything</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-wrangling/-/tree/main/source/notebooks/scraping">
            <img
              src="{{ url_for('static', filename='img/collecting.png') }}"
              alt="Data gathering"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Data gathering</h2>
                <p class="recipe-badge badge1">Scraping</p>
                <p class="recipe-badge badge2">Crawling</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/data-wrangling/-/tree/main/source/notebooks/databases">
            <img
              src="{{ url_for('static', filename='img/databases.png') }}"
              alt="Databases"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Databases</h2>
                <p class="recipe-badge badge1">Select</p>
                <p class="recipe-badge badge2">Simple</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes/templates/recipes/deep_learning.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/deep-learning/-/tree/main/source/notebooks/nn">
            <img
              src="{{ url_for('static', filename='img/traditional.png') }}"
              alt="Traditional dreamscape"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">Traditional Neural Networks</h2>
                <p class="recipe-badge badge1">Perceptron</p>
                <p class="recipe-badge badge2">Neurons</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/deep-learning/-/tree/main/source/notebooks/cnns">
            <img
              src="{{ url_for('static', filename='img/cnns.png') }}"
              alt="CNNs"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">Convolutional Neural Networks</h2>
                <p class="recipe-badge badge1">Mostly images</p>
                <p class="recipe-badge badge2">Tensorflow</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/deep-learning/-/tree/main/source/notebooks/nltk">
            <img
              src="{{ url_for('static', filename='img/nlp.png') }}"
              alt="NLP"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">Natural Language Processing</h2>
                <p class="recipe-badge badge1">NLP</p>
                <p class="recipe-badge badge2">Gutenberg</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/deep-learning/-/tree/main/source/notebooks/rnns">
            <img
              src="{{ url_for('static', filename='img/rnns.png') }}"
              alt="RNNs"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">Recurrent Neural Networks</h2>
                <p class="recipe-badge badge1">Forward pass</p>
                <p class="recipe-badge badge2">Stock predictions</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/deep-learning/-/tree/main/source/notebooks/advanced_rnns">
            <img
              src="{{ url_for('static', filename='img/advanced_rnns.png') }}"
              alt="Advanced RNNs"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">LSTMs, GRUs, and Advanced RNNs</h2>
                <p class="recipe-badge badge1">Comparison</p>
                <p class="recipe-badge badge2">Time/Accuracy</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/deep-learning/-/tree/main/source/notebooks/gans">
            <img
              src="{{ url_for('static', filename='img/gans.png') }}"
              alt="Gans"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">Generative Adversarial Networks</h2>
                <p class="recipe-badge badge1">Generator</p>
                <p class="recipe-badge badge2">Discriminator</p>
            </div>
        </a>
    </div>


</div>
{% endblock %}

project/recipes/templates/recipes/ml.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">


<div class="card">
        <a href="https://gitlab.com/tymyrddin/ml/-/tree/main/source/notebooks/preprocessing">
            <img
              src="{{ url_for('static', filename='img/telescope.png') }}"
              alt="Telescope"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Data preprocessing</h2>
                <p class="recipe-badge badge1">Crudely built</p>
                <p class="recipe-badge badge2">Hut</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ml/-/tree/main/source/notebooks/unsupervised_algorithms">
            <img
              src="{{ url_for('static', filename='img/clustering.png') }}"
              alt="Clustering"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Unsupervised learning algorithms</h2>
                <p class="recipe-badge badge1">Untagged data</p>
                <p class="recipe-badge badge2">Mimicry</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ml/-/tree/main/source/notebooks/supervised_metrics">
            <img
              src="{{ url_for('static', filename='img/throne_rooms.png') }}"
              alt="Throne rooms"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Supervised learning metrics</h2>
                <p class="recipe-badge badge1">Evaluation</p>
                <p class="recipe-badge badge2">Selection</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ml/-/tree/main/source/notebooks/supervised_algorithms">
            <img
              src="{{ url_for('static', filename='img/tagged.png') }}"
              alt="Tagged"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Supervised learning algorithms</h2>
                <p class="recipe-badge badge1">Input-output pairs</p>
                <p class="recipe-badge badge2">Mapping</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/ml/-/tree/main/source/notebooks/neural_networks">
            <img
              src="{{ url_for('static', filename='img/neural.png') }}"
              alt="Neural network"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">Classification</h2>
                <p class="recipe-badge badge1">Neural networks</p>
                <p class="recipe-badge badge2">AI</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes/templates/recipes/mlops.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('recipes.titanic_recipes') }}">
            <img
                src="{{ url_for('static', filename='portfolio/7.jpg') }}"
                alt="DL"
                class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Titanic survival</h2>
                <p class="recipe-badge badge1">Example pipe</p>
                <p class="recipe-badge badge2">Binary classification</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.ames_recipes') }}">
            <img
                src="{{ url_for('static', filename='portfolio/8.jpg') }}"
                alt="Dent's house"
                class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Ames housing prices</h2>
                <p class="recipe-badge badge1">Example pipe</p>
                <p class="recipe-badge badge2">Continuous regression</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://roadmaps.tymyrddin.dev/">
            <img
              src="{{ url_for('static', filename='portfolio/roadmaps.png') }}"
              alt="Neural network"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">Roadmaps</h2>
                <p class="recipe-badge badge1">Generic</p>
                <p class="recipe-badge badge2">MLOps</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes/templates/recipes/nlp.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/nlp/-/tree/main/source/notebooks/setup">
            <img
              src="{{ url_for('static', filename='img/setup.png') }}"
              alt="Setup"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Set up services</h2>
                <p class="recipe-badge badge1">AI</p>
                <p class="recipe-badge badge2">ML AWS</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="https://gitlab.com/tymyrddin/nlp/-/tree/main/source/notebooks/docs">
            <img
              src="{{ url_for('static', filename='img/docs.png') }}"
              alt="Docs"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Analysing documents and text</h2>
                <p class="recipe-badge badge1">Comprehend</p>
                <p class="recipe-badge badge2">Lambda functions</p>
            </div>
        </a>
    </div>
</div>
{% endblock %}

project/recipes/templates/recipes/recipe_starter.html
{% extends "recipe.html" %}

{% block recipe_description %}
    <h2><a href="">...</a></h2>
<p>...</p>
{% endblock %}

{% block recipe_image %}
<img src="{{ url_for('static', filename='img/....jpg') }}"  alt="..." />
{% endblock %}

{% block recipe_tips %}
<p>...</p>
{% endblock %}

{% block recipe_ingredients %}
<h2>List of Ingredients</h2>
<ul>
    <li>...</li>
</ul>
{% endblock %}

{% block recipe_steps %}
<h2>Resources</h2>
<ol>
    <li><a href="">...</a></li>
</ol>
{% endblock %}

project/recipes/templates/recipes/recipes.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('recipes.nlp_recipes') }}">
            <img
                src="{{ url_for('static', filename='portfolio/1.jpg') }}"
                alt="DL"
                class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Natural Language Processing</h2>
                <p>Appetiser ingredients</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.data_visualisation_recipes') }}">
            <img
                src="{{ url_for('static', filename='portfolio/6.jpg') }}"
                alt="DL"
                class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Data visualisation</h2>
                <p>Appetiser ingredients</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.deep_learning_recipes') }}">
            <img
                src="{{ url_for('static', filename='portfolio/4.jpg') }}"
                alt="DL"
                class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Deep learning</h2>
                <p>Appetiser ingredients</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.data_analysis_recipes') }}">
            <img
                src="{{ url_for('static', filename='portfolio/5.jpg') }}"
                alt="DA"
                class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Data analysis</h2>
                <p>10 recipes</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.ml_recipes') }}">
            <img
                src="{{ url_for('static', filename='portfolio/3.jpg') }}"
                alt="ML"
                class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Machine learning</h2>
                <p>Appetiser ingredients</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.data_wrangling_recipes') }}">
            <img
                src="{{ url_for('static', filename='portfolio/2.jpg') }}"
                alt="Data Wrangling"
                class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Data Wrangling</h2>
                <p>Appetiser ingredients</p>
            </div>
        </a>
    </div>


    <div class="card">
        <a href="{{ url_for('recipes.mlops_recipes') }}">
            <img
                src="{{ url_for('static', filename='portfolio/pipelines.png') }}"
                alt="ML"
                class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">MLOps</h2>
                <p>Simple desserts</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}