project/blog/__init__.py
"""
The `blog` blueprint handles displaying blog posts.
"""
from flask import Blueprint

blog_blueprint = Blueprint("blog", __name__, template_folder="templates")

from . import routes

project/blog/routes.py
from . import blog_blueprint
from flask import render_template, abort


blog_post_titles = [
    "packaging-models",
    "chaotic-order",
    "ml-ops",
    "security-scanning",
    "code-quality",
    "moon",
    "ml-pain-points",
]


@blog_blueprint.route("/blog/")
def blog():
    return render_template("blog/blog.html")


@blog_blueprint.route("/<blog_title>/")
def posts(blog_title):
    if blog_title not in blog_post_titles:
        abort(404)

    return render_template(f"blog/{blog_title}.html")


@blog_blueprint.route("/about/")
def about():
    return render_template("blog/about.html")


@blog_blueprint.route("/reservations/")
def reservations():
    return render_template("blog/reservations.html")

project/blog/templates/blog/about.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/page_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/material.css') }}" type="text/css">
{% endblock %}

{% block content %}
<div class="page-container">

    <div class="page__article">
        <h1>About Milliways</h1>
        <hr class="light">
        <p>Milliways, better known as the Restaurant at the End of the Universe, is a five-star restaurant situated at the end of time and matter. </p>
        <p>The Restaurant has some of the most staggeringly extravagant decor ever seen, a variety of the strangest guests from throughout history, and serves a particularly fine Pan Galactic Gargle Blaster. Milliways is run by an incredible arrangement of life forms from everywhen, and is the one place anywhen that serves talking food. Its main attraction is allowing diners to view a Gnab Gib, before desserts are served.</p>
    </div>

    <div class="page__article_white">
        <h1>At Your Service</h1>
        <hr class="light">
        <div class="row">
          <div class="column service-box">
              <em class="material-icons md-64 text-primary">usb</em>
              <h3>Works with your device</h3>
              <p class="text-muted">The Babel fish is a small, bright yellow fish, which can be placed in someone's ear in order for them to be able to hear any language translated into their first language. Meanwhile, the poor Babel fish, by effectively removing all barriers to communication between different races and cultures, has caused more and bloodier wars than anything else in the history of creation.</p>
          </div>
          <div class="column service-box">
              <em class="fa fa-4x fa-paper-plane text-primary"></em>
              <h3>Transportation</h3>
              <p class="text-muted">Near-instant transportation to the restaurant can be achieved in certain rarefied circumstances, such as being next to an exploding hyperspatial field generator on the planet where Milliways will eventually be built several billion years after the explosion occurs. Or have access to an Infinite Improbability Drive, such as The Heart of Gold.</p>
          </div>
          <div class="column service-box">
              <em class="fa fa-4x fa-solid fa-newspaper text-primary"></em>
              <h3>Up to Date</h3>
              <p class="text-muted">Far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy lies a small unregarded yellow sun. Orbiting this at a distance of roughly ninety-two million miles is an utterly insignificant little blue-green planet whose ape-descended life forms are so amazingly primitive that they still think digital watches are a pretty neat idea.</p>
          </div>
          <div class="column service-box">
              <em class="fa fa-4x fa-heart text-primary"></em>
              <h3>With Love</h3>
              <p class="text-muted">Protect me from knowing what I don’t need to know. Protect me from even knowing that there are things to know that I don’t know. Protect me from knowing that I decided not to know about the things that I decided not to know about. Amen.</p>
              <p class="text-muted">‘Forty-two,’ said Deep Thought, with infinite majesty and calm.</p>
          </div>
        </div>
    </div>

    <div class="page__article">
        <h1>Payment</h1>
        <hr class="light">
        <p>The restaurant’s bill can be paid by depositing a penny in any bank account of the present time: by the end of the universe, the compound interest on that penny over the course of time after 170 quintillion years (short scale) will be enough to pay the extremely high bill.</p>
        <div class="page-post-card__link">
            <a href="{{ url_for('blog.reservations') }}">Book me a reservation!</a>
        </div>
    </div>

</div>
{% endblock %}

project/blog/templates/blog/blog.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blog_style.css') }}">
{% endblock %}

{% block content %}
<div class="blog-container">

    <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/notebook_to_code.jpg') }}"
          alt="Notebook to code"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <a href="{{ url_for('blog.posts', blog_title='packaging-models') }}">
                <h2 class="recipe-title-long">Packaging models for production</h2></a>
            <p>Packaging models with all the fundamental tools to build a scalable, testable and maintainable ML infrastructure.</p>
            <p class="blog-post-card__date">Published on May 1, 2022</p>
        </div>
    </div>

    <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/on_the_fly.png') }}"
          alt="On the fly architecture"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <a href="{{ url_for('blog.posts', blog_title='ml-ops') }}">
                <h2 class="recipe-title-long">ML operations</h2></a>
            <p>MLOps was born at the intersection of DevOps, Data Engineering, and Machine Learning, and is similar to DevOps. Backward planning ...</p>
            <p class="blog-post-card__date">Updated on April 27, 2022</p>
        </div>
    </div>

    <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/vuln-scanning.png') }}"
          alt="On the fly architecture"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <a href="{{ url_for('blog.posts', blog_title='security-scanning') }}">
                <h2 class="recipe-title-long">Security scanning</h2></a>
            <p>None of the tools or databases will catch everything, and most are not sufficient for Conda or Docker containers because they only understand Python packages.</p>
            <p class="blog-post-card__date">Published on April 18, 2022</p>
        </div>
    </div>

    <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/black.png') }}"
          alt="Black Pycharm"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <a href="{{ url_for('blog.posts', blog_title='code-quality') }}">
                <h2 class="recipe-title-long">Notebook code quality</h2></a>
            <p>We use notebooks for the development of quality code snippets intended to become useful in future development projects. So we want Quality.</p>
            <p class="blog-post-card__date">Published on April 11, 2022</p>
        </div>
    </div>

    <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/moon_phases.png') }}"
          alt="Moon phases"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <a href="{{ url_for('blog.posts', blog_title='moon') }}">
                <h2 class="recipe-title-long">Full moons</h2></a>
            <p>All matter on Earth, both live and inert, experiences the effects of the gravitational forces of the Sun and Moon expressed in the form of tides.</p>
            <p class="blog-post-card__date">Published on April 9, 2022</p>
        </div>
    </div>

    <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/hidden_debt.png') }}"
          alt="Hidden debt"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <a href="{{ url_for('blog.posts', blog_title='ml-pain-points') }}">
                <h2 class="recipe-title-long">ML pain points</h2></a>
            <p>Machine Learning systems are still experimental in nature and have more components that are significantly more complex to build and operate.</p>
            <p class="blog-post-card__date">Published on March 12, 2022</p>
        </div>
    </div>

        <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/data-science-chaos.png') }}"
          alt="Data science chaos"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <a href="{{ url_for('blog.posts', blog_title='chaotic-order') }}">
                <h2 class="recipe-title-long">Chaotic order code base</h2></a>
            <p>Some steps need to be done before others, like initial explorations before sensible cleaning, and cleaning before feature engineering, but after that it gets chaotic.</p>
            <p class="blog-post-card__date">Published on March 11, 2022</p>
        </div>
    </div>

</div>
{% endblock %}

project/blog/templates/blog/blogpost_starter.html
{% extends "blogpost.html" %}

{% block title %}
<h1>...</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on April 26, 2022</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/....png') }}"
  alt="..."
  class="blogpost__image" />
{% endblock %}

{% block article %}
<p>...</p>
<p>...</p>
{% endblock %}

project/blog/templates/blog/chaotic-order.html
{% extends "blogpost.html" %}

{% block title %}
<h1>Chaotic order code base</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on March 11, 2022</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/data-science-chaos.png') }}"
  alt="Data science chaos"
  class="blogpost__image" />
{% endblock %}

{% block article %}
    <p>As the importance of data science has grown, so too has the body of jargon associated with it. While many terms of art are well-defined, others are buzzwords, ubiquitous in the media but lacking concrete meaning.</p>
    <p>Also, data science is not linear, although some steps need to be done before others, like initial explorations before sensible wrangling, and wrangling before preprocessing and/or feature engineering, but after that it gets chaotic. For example, some models do not work well with simple label encoding, and with feature engineering creativity based on understanding the domain, and on how features are correlated.</p>
    <p>This where the puzzling fun really starts.</p>
    <p>It does make sense to first create a skeleton and make "steps" to practice some used techniques:</p>
    <ul>
        <li><a href="{{ url_for('recipes.data_wrangling_recipes') }}">Data wrangling</a></li>
        <li><a href="{{ url_for('recipes.ml_recipes') }}">Machine learning</a></li>
        <li><a href="{{ url_for('recipes.data_visualisation_recipes') }}">Data visualisation</a></li>
        <li><a href="{{ url_for('recipes.data_analysis_recipes') }}">Data analysis</a></li>
        <li><a href="{{ url_for('recipes.deep_learning_recipes') }}">Deep learning</a></li>
        <li><a href="{{ url_for('recipes.nlp_recipes') }}">Natural language processing</a></li>
    </ul>

    <p>We develop reuseful snippets using Jupyter notebooks and public datasets, to gradually build towards functions and classes for (other) projects later.</p>
{% endblock %}

project/blog/templates/blog/code-quality.html
{% extends "blogpost.html" %}

{% block title %}
<h1>Notebook code quality</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on April 11, 2022</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/black.png') }}"
  alt="Black"
  class="blogpost__image" />
{% endblock %}

{% block article %}
    <p>A read–eval–print loop (REPL) such as Jupyter Notebook offers, is a simple interactive computer
        programming environment that takes single user inputs, executes them, and returns the result.
        This facilitates quick feedback during development and allows for developing code at a faster speed
        than if it had to be run as one monolithic piece of code.</p>
    <p>The way Jupyter Notebook works with code in blocks, which can be run independently, makes it easier to
        experiment and trial certain operations without having to re-run the full workflow. Ideal for analysis tasks that require both numerical and visual outputs.</p>
    <p>Not so ideal when trying to leverage notebooks for production use rather than an analytical use case.
        And in our case, we wish to produce a quality snippet code base reuseful for future
        production projects.</p>
    <p>So we want Quality.</p>

    <h2>Black-Jupyter</h2>
    <p>We do code formatting with <a href="https://anaconda.org/conda-forge/black-jupyter">black-jupyter</a>.
        Running Black Jupyter on all notebooks from the root of a repo is as simple as:</p>
    <code>$ black .</code>

    <h2>Flake8_nb</h2>
    <p>We check PEP8 compliance with <a href="https://anaconda.org/conda-forge/flake8-nb">flake8_nb</a>.
        Running Flake8 NB on all notebooks from the root of a repo:</p>
    <code>$ flake8_nb notebooks</code>

    <h2>Automation with pre-commit</h2>
    <p>We automated the code formatting and PEP8 compliance processes by using the
        <a href="https://anaconda.org/conda-forge/pre_commit">pre-commit framework</a> and its
        <a href="https://anaconda.org/conda-forge/pre-commit-hooks">hooks</a>.</p>
    <p>It runs a short script before committing. If the script passes, then the commit is made, else,
        the commit is denied (and we fix whatever is up).</p>

    <h2>Mypy</h2>
    <p>For additional type annotations we installed <a href="https://anaconda.org/anaconda/mypy">mypy</a> with
        <a href="https://anaconda.org/conda-forge/data-science-types">data-science-types</a> for libraries
        like matplotlib, numpy and pandas that do not have type information, and
        <a href="https://anaconda.org/conda-forge/nbqa">nbqa</a>.
        Run on all notebooks in the root directory of a repo with:</p>
    <code>$ nbqa mypy .</code>

    <p>To be continued ...</p>
{% endblock %}

project/blog/templates/blog/ml-ops.html
{% extends "blogpost.html" %}

{% block title %}
<h1>ML operations</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on March 17, 2022</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/on_the_fly.png') }}"
  alt="On the fly architecture"
  class="blogpost__image" />
{% endblock %}

{% block article %}
    <p>Issues with reproducibility appeared. Conda did help some. Our objective is building our own pipeline infrastructure with an eye out for reproducibility issues, enabling us to easily plug in any future model as a microservice.</p>
    <p>MLOps was born at the intersection of DevOps, Data Engineering, and Machine Learning, and is similar to DevOps. The execution is different. For a smart and balanced approach, we wished to anticipate our learning path somewhat, so we visited data science and forums, made lists of <a href="{{ url_for('blog.posts', blog_title='ml-pain-points') }}">operations and testing painpoints</a>, and ordered those in an inductive scenario.</p>
    <p>Our backward planning path could look something like this:</p>
    <ul>
        <li>Each new idea is a new Jupyter notebook. Keeping a common codebase will get hard.</li>
        <li>We create a separate git repository, in which we extract a notebook of the playground codebase and make a development model notebook, then create a Python package for production from it.</li>
        <li>We aim at high test coverage, use type hints and pay attention to code quality. But with machine learning code, it is not always that simple. To test model code correctly, we would need to train the model. Even with a small data subset, too long for a unit test. Plus that the model trained on a small data subsample does not behave like the model trained on an entire, real dataset.</li>
        <li>Mypy finds issues with parts of the code that unit tests do not cover. Seeing that a function receives, or returns, something else than we expected is a simple but powerful check.</li>
        <li>We decide to drop some unit tests and run smoke tests. For every new pull request, we train the model in a production-like environment, on a full dataset, with the only exception that the hyperparameters are set to value that lead to getting the results fast. We monitor this pipeline for any problems, and catch them early.</li>
        <li>Our datasets will become larger at some point and so will our use of more powerful cloud solutions. Having environment configurations that we can trust becomes essential. Dockers enable us to have unified, sealed setups (codebase, package versions, system dependencies, configurations), no matter who and where is running it. We can now launch Jupyter from inside the container, save the hash of all the code for versioning and generate results. We store everything in git, greatly improving the reproducibility and traceability of our codebase and model changes.</li>
        <li>We can now move between different execution environments (Docker), tests are set up, and we can add continuous integration to make checks and reviews more efficient. We move all code checks into the Docker, including unifying versions and configurations. For local development, we use a makefile to build the image, run it, and run all the checks and tests on the code.</li>
        <li>Now we wish to be able to test a model for multiple datasets of different clients in different scenarios. Something we do not want to set up and run manually. We need orchestration, automated pipelines, and plugging it into the production environment easily. Docker makes it easy to move between different environments (local and cloud), and also makes it possible to connect it into the production pipeline directly as a microservice by writing a few YAMLs.</li>
        <li>Now how to manage all those model versions? We need to monitor the results of multiple models, trained on multiple datasets, with different parameters and metrics. And we want to be able to compare all those model versions with each other. MLFlow and Neptune are basically our main options. Neptune is more of an out-of-the-box solution enabling us to tag the experiments, save the hyperparameters, model version, metrics, and plots in a single place. And we choose less dependency and for MLFlow.</li>
        <li>Most likely, we wish to train a separate model for each application type with constantly growing time-series datasets. And we may wish to have a model that predicts multiple characteristics of an application. We decide to pack models into microservices for making replacing one service with another possible (using the same interface) by using FastAPI.</li>
        <li>How do we make sure that the model provides good insights (and not just good machine learning metrics)? Producing a static web page with plots and statistics describing the results of training does not scale that well. Automating it? Garbage in, garbage out! We will need a domain expert audit of every trained model’s results.</li>
    </ul>

    <p>Now we can aim for an architecture which enables us to easily plug in any future model as a microservice.</p>
{% endblock %}

project/blog/templates/blog/ml-pain-points.html
{% extends "blogpost.html" %}

{% block title %}
<h1>ML pain points</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on March 12, 2022</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/hidden_debt.png') }}"
  alt="Hidden debt"
  class="blogpost__image" />
{% endblock %}

{% block article %}
<p>Machine Learning systems are experimental in nature and have more components that are significantly more complex to build and operate.</p>
<ul>
    <li>In general, the more data, the better the model, and where is the data coming from? Open source and free, publicly available for a price, privately owned by a few private people? If it doesn’t already exist, where and how are we going to mine it? Would we be asked to steal private data or data that can assist in de-anonymisation practices (not an ethically acceptable proposal)?</li>
    <li>Many of the important and useful algorithms are open source. Not all. When the datasets are small, a model can produce biased results. Is it okay to reverse engineer an algorithm that produces better results? Alternatives are to develop, buy, or report failure and why.</li>
    <li>When reporting the accuracy of a model, the results a model produced are compared to actual answers. The closer they are, the higher the accuracy.  Using the same set, or manufacturing a synthetic set to fit the model are not an option.  Sadly, many apparently still do this.</li>
    <li>Besides all the efforts and tools, the ML/DL industry still struggles with the reproducibility of experiments.</li>
    <li>The team needed to build and deploy models in production usually includes data scientists or ML researchers, who focus on exploratory data analysis, model development, and experimentation. They might not be experienced software engineers who can build production-class services.</li>
    <li>Moving to the cloud.</li>
    <li>Even with a small data subset, testing model code can be too long for a unit test, and a model trained on a small data subsample does not behave like the model trained on an entire, real dataset. A possible solution is to drop some unit tests and run smoke tests. For every new pull request, train the model in a production-like environment, on a full dataset, with the only exception that the hyperparameters are set to value that lead to getting the results fast. Then monitor this pipeline for any problems, and catch them early, and add continuous integration to make checks and reviews more efficient.</li>
    <li><a href="{{ url_for('recipes.titanic_recipes') }}">Creating and managing ML pipelines</a>: An offline-trained ML model can not simply be deployed as a prediction service. This requires a multistep pipeline to automatically retrain and deploy a model. Such a pipeline adds complexity because the steps that data scientists do manually to train and validate new models need to be automated.</li>
    <li>ML models in production can have reduced performance not only due to suboptimal coding but also due to constantly evolving data profiles. Models can decay in more ways than conventional software systems. This can be caused by:
        <ul>
            <li>A discrepancy between data is handled in the training and in the serving pipelines.</li>
            <li>A change in the data between training and serving.</li>
            <li>A feedback loop – Choosing the wrong hypothesis (i.e. objective) for optimisation, can make us collect biased data for training models. When collecting newer data points using this flawed hypothesis, it is fed back in to future versions of the model, making the model even more biased, and the snowball keeps growing.</li>
        </ul></li>
    <li>Scaling.</li>
    <li>Dealing with sensitive data at scale.</li>
    <li>In order to be able to refresh models in production when needed, these and summary statistics of data that built a model need to be monitored. These statistics can and will change over time. Notifications and a roll-back process are required for when values deviate from expectations.</li>
</ul>
{% endblock %}

project/blog/templates/blog/moon.html
{% extends "blogpost.html" %}

{% block title %}
<h1>Full moons</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on April 9, 2022</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/moon_phases.png') }}"
  alt="Moon phases"
  class="blogpost__image" />
{% endblock %}

{% block article %}
    <em>All matter on Earth, both live and inert, experiences the effects of the gravitational
        forces of the Sun and Moon expressed in the form of tides. The periodic oscillations
        exhibit two daily cycles and are modulated monthly and annually by the motions of
        these two celestial bodies. All organisms on the planet have evolved in this context.</em>

    <p>A <a href="https://agencia.fapesp.br/gravitational-action-of-sun-and-moon-influences-behavior-of-animals-and-plants-study-shows/37629/">new study</a>
        finds that all biological organisms, from plants, to animals, to human beings, all have a
        connection to the gravitational forces coming from the Sun and Moon. Science heading for (common) ground.</p>

    <p>Although the exact mechanism of the moon's influence on earth, humans and animals awaits
        further scientific exploration, finding correlations between target features and moon
        cycles may be helpful in relevant data science projects such as in health research,
        and for example, for predicting earthquakes and floods.</p>

    <p>Today, most countries on Earth are using the Julian calendar. It was introduced by Julius Caesar
        in 45 BCE and replaced the Roman moon based calendar. This predecessor was a very complicated
        lunar calendar. It required a group of people to decide when days should be added or removed in
        order to keep the calendar in sync with the solar seasons, marked by equinoxes and solstices.</p>

    <p>We can scrape the
        <a href="https://www.fullmoon.info/en/fullmoon-calendar_1900-2050.html">Fullmoon Calendar website</a>
        for a dataset of full moons that can be merged into time series datasets for correlation purposes:
        The <a href="https://gitlab.com/tymyrddin/data-wrangling/-/blob/main/notebooks/scraping/moon.ipynb">code</a>,
        and the <a href="https://gitlab.com/tymyrddin/data-wrangling/-/tree/main/notebooks/scraping/assets">1900-2050 full moon datasets</a>.</p>

{% endblock %}

project/blog/templates/blog/reservations.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/page_style.css') }}">
{% endblock %}

{% block content %}
<div class="page-container">

    <div class="page__article">
        <h1>Reservations</h1>
        <hr class="light">
        <p>Reservations are easily obtained, since they can be booked once you, as our patron, return to your original time and location after your meal.</p>
        <p>We hope you enjoyed your stay with us. Ready to make that reservation?</p>
    </div>

    <style>
        .honey {
            opacity: 0;
        }
    </style>

    <div class="page__article form">
        <form name="contact" method="POST" netlify-honeypot="bot-field" data-netlify="true">
          <p class="honey">
              <label>
                  Don’t fill this out if you’re human: <input name="bot-field" />
              </label>
          </p>
          <p>
            <label>Name: <input type="text" placeholder="eg. Corporal Cheery (or Cheri) Littlebottom" name="name" /></label>
          </p>
          <p>
            <label>Email: <input type="email" placeholder="eg. littlebottom@lscpace.org" name="email" /></label>
          </p>
          <p>
            <label>Message: <textarea placeholder="eg. Please book me a table for two by the window." name="message"></textarea></label>
          </p>
          <p>
            <input type="submit" value="Send">
          </p>
        </form>
    </div>

</div>
{% endblock %}

project/blog/templates/blog/security-scanning.html
{% extends "blogpost.html" %}

{% block title %}
<h1>Security scanning</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on April 18, 2022</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/vuln-scanning.png') }}"
  alt="Snyk as Pycharm extension"
  class="blogpost__image" />
{% endblock %}

{% block article %}
    <p>None of the tools or underlying databases will catch everything, and security vulnerability
        scanners that are built for checking Python dependencies are not sufficient for Conda or
        Docker containers because they only understand Python packages. Conda combines Python
        dependencies and system packages and basing docker containers on existing containers
        could open up a can of worms.</p>

    <h2>Safety</h2>
    <p><a href="https://anaconda.org/conda-forge/safety">Safety</a> checks installed dependencies
        for known security vulnerabilities. By default, it uses the open Python vulnerability database
        <a href="https://github.com/pyupio/safety-db/tree/master/data">Safety DB</a> (updated every month),
        and can be upgraded to use pyup.io's
        <a href="https://github.com/pyupio/safety/blob/master/docs/api_key.md">Safety API</a> (a paid service).</p>

    <code>$ safety check</code>

    <h2>Jake</h2>
    <p>We need a tool that knows about all the different types of software that end up in the Conda package
        repositories, beyond just checking Python libraries. <a href="https://anaconda.org/conda-forge/jake">Jake</a>
        supports Conda packages and relies on the
        <a href="https://ossindex.sonatype.org/">Sonatype OSS Index of security vulnerabilities</a>.</p>
    <code>$ conda list | jake ddt -c | grep VULNERABLE</code>
    <p>Note that omitting that <code>-c</code>, it will give only Python vulnerabilities.</p>

    <h2>Snyk</h2>
    <p><a href="https://docs.docker.com/engine/scan/">Docker scan</a> runs on <a href="https://snyk.io/docker/">Snyk engine</a> for checking security state of container images.</p>

    <p>To be continued ...</p>

{% endblock %}